version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: taskdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./flask-backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
    volumes:
      - ./flask-backend:/app

  frontend:
    build: ./react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
